{
 "title": "MySQL-Metrics Copy",
 "description": "This dashboard provides basic performance metrics for mysql/mariadb.\r\n\r\nUses Telegraf built-in plugin",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "mysql" },
   { "name": "host", "label": "Host" },
   { "name": "interval", "label": "Interval", "query": "10s,1m,5m,15m,1h,6h,1d" },
   {
    "name": "table_open_cache",
    "label": "table_open_cache",
    "query": "select cast(@@table_open_cache as signed)"
   }
  ]
 },
 "panels": [
  { "title": "Blocking (Non-Historical)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Blocking Transactions(LIVE)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT blocking_thread_id as blocker, requesting_thread_id as waiter\r\nFROM performance_schema.data_LOCK_WAITS;"
    }
   ]
  },
  {
   "title": "Blockers",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "\nselect processlist_user as username, processlist_host as host, processlist_time as seconds,  processlist_state as state, processlist_info as commands\nfrom performance_schema.threads \nwhere thread_id in (select blocking_thread_id FROM performance_schema.data_LOCK_WAITS); \n"
    }
   ]
  },
  {
   "title": "Waiters",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select processlist_user as username, processlist_host as host, processlist_time as seconds,  processlist_state as state, processlist_info as commands\nfrom performance_schema.threads \nwhere thread_id in (select requesting_thread_id FROM performance_schema.data_LOCK_WAITS);"
    }
   ]
  },
  {
   "title": "General Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MySQL Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Connections per second",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(connections), 1s) from \"mysql\" WHERE  \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name in ('THREADS_CONNECTED')\nORDER BY time_sec ASC\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ],
       "target": "alias(perSecond(servers.$host.mysql-status.counter-Connections), 'Connections')"
      },
      {
       "alias": "Max used connections",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(max_used_connections) from \"mysql\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ],
       "target": "alias(perSecond(servers.$host.mysql-status.gauge-Max_used_connections), 'Max used connections')"
      }
     ]
    },
    {
     "title": "(Stacked) MySQL Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Threads connected",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'Threads_connected' AND \"type\" = 'gauge' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED) as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name in ('THREADS_RUNNING')\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ],
       "target": "alias(servers.$host.mysql-status.gauge-Threads_connected, 'Threads connected')"
      },
      {
       "alias": "Threads running",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'Threads_running' AND \"type\" = 'gauge' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ],
       "target": "alias(servers.$host.mysql-status.gauge-Threads_running, 'Threads running')"
      }
     ]
    },
    {
     "title": "Current MySQL Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "SELECT last(value) FROM \"mysql_value\" WHERE \"instance\" = 'status' AND \"type_instance\" = 'Uptime' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED) as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name = 'UPTIME'\r\nORDER BY time_sec ASC\r\n",
       "target": "servers.$host.mysql-status.gauge-Uptime"
      },
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Current Queries",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "SELECT last(value) FROM \"mysql_value\" WHERE \"instance\" = 'status' AND \"type\" = 'counter' AND  \"type_instance\" = 'Queries' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
       "select": [
        [
         { "params": [ "queries" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "target": "perSecond(servers.$host.mysql-status.counter-Queries)"
      }
     ]
    },
    {
     "title": "MySQL Connection Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Data Out",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s)*8 from \"mysql_value\" WHERE \"type_instance\" = 'Bytes_sent' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  sum(cast(variable_value as SIGNED)/10) as value,\r\n  \"CONNECTION_ERRORS_xxx\" as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name in ('CONNECTION_ERRORS_ACCEPT-d','CONNECTION_ERRORS_INTERNAL-d','CONNECTION_ERRORS_MAX_CONNECTIONS-d','CONNECTION_ERRORS_PEER_ADDRESS-d','CONNECTION_ERRORS_SELECT-d','CONNECTION_ERRORS_TCPWRAP-d')\r\nORDER BY time_sec ASC",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Data In",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "SELECT derivative(mean(\"bytes_received\"), 1s) FROM \"mysql\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Table Locks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "alias": "Table Locks Immediate",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Table_locks_immediate' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name = 'INNODB_ROW_LOCK_WAITS-d'\nORDER BY time_sec ASC\n\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Table Locks Waited",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Table_locks_waited' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name = 'COM_LOCK_TABLES-d'\nORDER BY time_sec ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "(Stacked) MySQL Select Types",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Select Full Join",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Select_full_join' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Select Full Range Join",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Select_full_range_join' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED)/600 as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name in ('COM_INSERT_SELECT-d','COM_REPLACE_SELECT-d','COM_SELECT-d','CONNECTION_ERRORS_SELECT-d','SELECT_FULL_JOIN-d','SELECT_FULL_RANGE_JOIN-d','SELECT_RANGE-d','SELECT_RANGE_CHECK-d','SELECT_SCAN-d')\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Select Range",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Select_range' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Select Range Check",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Select_range_check' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Select Scan",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Select_scan' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Temporary Objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 10, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Created Tmp Tables",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Created_tmp_tables' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED)/600 as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name IN ( 'CREATED_TMP_TABLES-d')\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Created Tmp Disk Tables",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Created_tmp_disk_tables' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Created Tmp Files",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Created_tmp_files' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Slow Queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Slow Queries Per Second",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Slow_queries' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name = 'SLOW_QUERIES-d'\nORDER BY time_sec asc\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "(Stacked) MySQL Sorts",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Sort Rows",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Sort_rows' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED)/600 as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name in ('SORT_SCAN-d', 'SORT_ROWS-d', 'SORT_RANGE-d', 'SORT_MERGE_PASSES-d')\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Sort Range",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Sort_range' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Sort Merge Passes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Sort_merge_passes' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Sort Scan",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Sort_scan' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Aborted Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Ops/10-Min" } },
     "targets": [
      {
       "alias": "Aborted Clients (timeout)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Aborted_clients' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED) as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name = 'ABORTED_CONNECTS-d'\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Aborted Connects (attempts)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Aborted_connects' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Command, Handlers, Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Command Counters",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Com_insert",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_insert' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_update",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_update' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED)/600 as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name in ('COM_SELECT-d', 'COM_UPDATE-d', 'COM_DELETE-d', 'COM_INSERT-d')\nORDER BY time_sec ASC\n\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_commit",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_commit' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_begin",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_begin' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_admin_commands",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_admin_commands' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_show_status",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_show_status' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_show_variables",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_show_variables' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_set_options",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_set_options' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Top Command Counters  24 hours",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Com_insert",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_insert' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_insert" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_update",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_update' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_update" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_commit",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_commit' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_commit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_begin",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_begin' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_begin" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_admin_commands",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_admin_commands' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_admin_commands" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_show_status",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_show_status' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_show_status" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_show_variables",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_show_variables' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_show_variables" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Com_set_options",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Com_set_options' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "commands_set_option" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "(Stacked) MySQL Handler",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "Handler_read_key",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_read_key' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED)/600 as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name in ('HANDLER_COMMIT-d','HANDLER_DELETE-d','HANDLER_DISCOVER-d','HANDLER_EXTERNAL_LOCK-d','HANDLER_MRR_INIT-d','HANDLER_PREPARE-d','HANDLER_READ_FIRST-d','HANDLER_READ_KEY-d','HANDLER_READ_LAST-d','HANDLER_READ_NEXT-d','HANDLER_READ_PREV-d','HANDLER_READ_RND-d','HANDLER_READ_RND_NEXT-d','HANDLER_ROLLBACK-d','HANDLER_SAVEPOINT-d','HANDLER_SAVEPOINT_ROLLBACK-d','HANDLER_UPDATE-d','HANDLER_WRITE-d')\nORDER BY time_sec ASC\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_read_rnd_next",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_read_rnd_next' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_write",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_write' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_update",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_update' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_delete",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_delete' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_commit",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_commit' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_discover",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_discover' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "(Stacked) MySQL Handler 24 hours",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Handler_read_key",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_read_key' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_read_key" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_read_rnd_next",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_read_rnd_next' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_read_rnd_next" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_write",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_write' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_write" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_update",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_update' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_update" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_delete",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_delete' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_delete" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_commit",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_commit' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_commit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Handler_discover",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Handler_discover' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "handler_discover" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MySQL Free Buffers Percentage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Free Memory",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_free_memory' AND \"type\" = 'gauge' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Query Cache Size",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'query_cache_size' AND \"type\" = 'gauge' AND \"instance\" = 'variables' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(x.TIMEST) as time_sec,\n  cast(x.variable_value as SIGNED)/cast(y.variable_value as SIGNED)*100 as value,\n  'Free Buffer%' as metric\nFROM my2.status x, my2.status y\nWHERE $__timeFilter(x.TIMEST) \nAND x.variable_name = 'INNODB_BUFFER_POOL_PAGES_FREE' \nAND y.variable_name = 'INNODB_BUFFER_POOL_PAGES_TOTAL'\nAND x.TIMEST = Y.TIMEST\nORDER BY time_sec ASC",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Query Cache Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "Hits",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_hits' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "qcache_hits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Inserts",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_inserts' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "qcache_inserts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Not Cached",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_not_cached' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "qcache_not_cached" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Prunes",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_lowmem_prunes' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "qcache_lowmem_prunes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "Queries in Cache",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Qcache_queries_in_cache' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "qcache_queries_in_cache" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Files and Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "MySQL File Openings",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Openings",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Opened_files' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED) as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name = 'OPEN_FILES-d'\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Table Openings",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Openings",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select derivative(mean(\"value\"),1s) from \"mysql_value\" WHERE \"type_instance\" = 'Opened_tables' AND \"type\" = 'counter' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\r\n  cast(variable_value as SIGNED) as value,\r\n  variable_name as metric\r\nFROM my2.status\r\nWHERE $__timeFilter(TIMEST) AND variable_name = 'OPEN_TABLES-d'\r\nORDER BY time_sec ASC\r\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Open Files",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Open Files",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'Open_files' AND \"type\" = 'gauge' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name = 'OPEN_FILES'\nORDER BY time_sec ASC\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "MySQL Open Tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Open Tables",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mysql",
       "query": "select mean(\"value\") from \"mysql_value\" WHERE \"type_instance\" = 'Open_tables' AND \"type\" = 'gauge' AND \"instance\" = 'status' AND \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(TIMEST) as time_sec,\n  cast(variable_value as SIGNED) as value,\n  variable_name as metric\nFROM my2.status\nWHERE $__timeFilter(TIMEST) AND variable_name = 'OPEN_TABLES'\nORDER BY time_sec ASC\n\n",
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}